
server:
  ip: 0.0.0.0
  port: 8090

database:
  dialect: "postgres"
  port: 54320
  dbuser: "postgres"
  dbpassword: "postgres"
  dbname: "ia_text"
  sslmode: "disable"
  showqueries: true
  dbcp:
    maxidle: 20
    maxactive: 200

cache:
  useCache: false
  dialect: "redis"
  network: "tcp"
  ip: "localhost"
  port: 63790
  pool:
    maxidle: 80
    maxactive: 12000

InitDatabase: true
DefaultLocale: en-US
ServiceOwnerSourceId: IA